

all:	HW1-1 HW1-2

HW1-1:	HW1-1.o
	g++  HW1-1.o -o HW1-1

HW1-1.o:	HW1-1.cpp
	g++ -c HW1-1.cpp

HW1-2:	HW1-2.o
	g++  HW1-2.o -o HW1-2

HW1-2.o:	HW1-2.cpp
	g++ -c HW1-2.cpp

clean:
	rm -f *.o HW1-1 HW1-2
